sudo: false
language: python
notifications:
  email:
    recipients:
      - chenjiandongx@qq.com
    on_success: always # default: change
    on_failure: always # default: always
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7
before_install:
  - pip install -r test/requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == "3.6" ]]; then pip install https://github.com/pyecharts/pyecharts-javascripthon/archive/master.zip; fi  
  - if [[ $TRAVIS_PYTHON_VERSION == "3.5" ]]; then pip install https://github.com/pyecharts/pyecharts-javascripthon/archive/master.zip; fi  
script:
  - python setup.py install
  - make tests
after_success:
  - cd test
  - codecov

