environment:

  matrix:
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - cd test
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install mock"
  - if [%PYTHON_VERSION%]==[3.5] "%PYTHON%\\python.exe -m pip install https://github.com/pyecharts/pyecharts-javascripthon/archive/master.zip"
  - if [%PYTHON_VERSION%]==[3.6] "%PYTHON%\\python.exe -m pip install https://github.com/pyecharts/pyecharts-javascripthon/archive/master.zip"
build: off

test_script:
  "%PYTHON%/Scripts/nosetests --with-coverage --cover-package pyecharts --cover-package test && cd .. && %PYTHON%/Scripts/flake8 --exclude docs --builtins=unicode,xrange,long"
